add R and IDE background
numbats/monash-learnr-modules pull request #22
Opened 2024-07-09 06:32 UTC by KrisanatA

2024-07-10 16:17 UTC, KrisanatA commented
@mitchelloharawild Could you have a look at the first module (installation), especially the Linux installation? Also, I am thinking of just using the screenshot instead of the video. What do you think? I used a step-by-step guide, so I think providing a screenshot for each step might be better.

2024-07-10 16:23 UTC, mitchelloharawild commented
Are you planning to add the screenshots? I think more detail is useful (especially for Linux for example).

2024-07-10 16:24 UTC, KrisanatA commented
Yes, since the old learnR already has all the screenshots.

2024-07-11 11:33 UTC, KrisanatA commented
@mitchelloharawild Could you have a look here [4269ae0](https://github.com/numbats/monash-learnr-modules/pull/22/commits/4269ae0453a1b4131ef8613a250b4675bd8d04a4)? Is there a way around for using the `install.packages` in webr? I noticed that to install the packages in webr I need to use a different function or call the `webr::shim_install`.

2024-07-11 11:41 UTC, mitchelloharawild commented
It should already work, because the function should be shimmed
automatically. If you use library with a package that isn't installed it
should also automatically install it.

On Thu, Jul 11, 2024, 1:33 PM Krisanat Anukarnsakulchularp <
***@***.***> wrote:

> @mitchelloharawild <https://github.com/mitchelloharawild> Could you have
> a look here 4269ae0
> <https://github.com/numbats/monash-learnr-modules/pull/22/commits/4269ae0453a1b4131ef8613a250b4675bd8d04a4>?
> Is there a way around for using the install.packages in webr? I noticed
> that to install the packages in webr I need to use a different function or
> call the webr::shim_install.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/numbats/monash-learnr-modules/pull/22#issuecomment-2222693947>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AD3BJF2S36MZAP5JLKGSAHLZLZURVAVCNFSM6AAAAABKSFPVBWVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDEMRSGY4TGOJUG4>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2024-07-11 11:51 UTC, KrisanatA commented
@mitchelloharawild This is the error I got when running install.packages("palmerpenguins") inside the webR: **This version of R is not set up to install source packages. If it was installed from an RPM, you may need the R-devel RPM**

2024-07-17 16:12 UTC, KrisanatA commented
@mitchelloharawild Could you have a look? Let me know if you have any suggestions.

2024-07-18 14:09 UTC, mitchelloharawild requested changes
Thanks, have a look at these comments/suggestions.

Please check for typos and spelling issues.

2024-07-18 14:09 UTC, mitchelloharawild commented on modules/installation/02-basics.qmd
> +There is a shortcut key for creating a new R Script, which is **shift + ctrl + N** for Windows and Linux or **shift + cmd + N** for Macs.
I think it's canonical for ctrl/cmd to be written first.

2024-07-18 14:09 UTC, mitchelloharawild commented on modules/installation/02-basics.qmd
> +Alternatively, you can install the package by running `install.packages("package_name")` in the ***Console** pane.
Typo `***` > `**`, please check the rest carefully.

2024-07-18 14:09 UTC, mitchelloharawild commented on modules/installation/02-basics.qmd
> +Let's start by purchasing a book (install the package). Through the interface, navigate to the "Packages" tab in the **Output** pane. It will show you what packages you currently have. Next, click "I
> purchasing a book (install the package) [...] you are now ready to start reading a book.

I think the analogy isn't needed here, especially if the emphasis is on the book and not the package.

2024-07-18 14:09 UTC, mitchelloharawild commented on modules/installation/02-basics.qmd
> +Let's start by purchasing a book (install the package). Through the interface, navigate to the "Packages" tab in the **Output** pane. It will show you what packages you currently have. Next, click "I
Some more work on the analogy could make it work if you think it is helpful, especially with graphics (books & hex stickers, bookshelf & system library, etc.)

2024-07-18 14:09 UTC, mitchelloharawild commented on modules/installation/02-basics.qmd
> +:::{.callout-caution}
This should have a "Your turn!" title, otherwise the output says 'Caution'

2024-07-18 14:09 UTC, mitchelloharawild commented on modules/installation/02-basics.qmd
> +You will hear people talk about the "base R". It refers to the pre-installed functions in R that get loaded every time you start R. It provides you with the basic functions. For example, the `sum()`
This is more commonly used to refer to a style/design of packages (in the style of 'base' packages), as opposed to the 'tidy R' style/design of packages.

2024-07-18 14:09 UTC, mitchelloharawild commented on modules/installation/02-basics.qmd
> +You will hear people talk about the "base R". It refers to the pre-installed functions in R that get loaded every time you start R. It provides you with the basic functions. For example, the `sum()`
Not sure if that fits here, you could say that R comes bundled with some basic packages that are always loaded, including `base` (for basic things like `+` and `log()`), `utils` (for utility functions like `install.packages()`), and `stats` (for statistical models like `lm()` and `arima()`).

2024-07-18 14:09 UTC, mitchelloharawild commented on modules/installation/02-basics.qmd
> +:::{.callout-important}
Another important thing to fit in somewhere is that packages need installing only once, and `install.packages()` shouldn't be kept (uncommented) in R code.

2024-07-18 14:10 UTC, mitchelloharawild commented
> @mitchelloharawild This is the error I got when running install.packages("palmerpenguins") inside the webR: **This version of R is not set up to install source packages. If it was installed from an RPM, you may need the R-devel RPM**

FYI I've fixed this in `main`: f9e44ec585fd9ca3b14107fd027abd30675fbdc4

2024-07-19 16:32 UTC, KrisanatA commented
@mitchelloharawild I have made changes to all of your suggestions.

2024-07-31 00:11 UTC, mitchelloharawild approved these changes
Looks great, nice work!

2024-07-31 00:12 UTC, merged